baseURL: "https://tamtamhihi.github.io/"
title: "tamtamhihi's blog"
pagination:
  pagerSize: 5
theme: PaperMod
publishDir: docs

menu:
  main:
    - name: Archives
      url: /archives/
      weight: 10
    - name: Search
      url: /search/
      weight: 5
#    - name: Tags
#      url: /tags/
#      weight: 5
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

enableEmoji: true

params:
  env: production
  title: tamtamhihi
  description: "tamtamhihi's blog"
  keywords: [Blog]
  author: tamtamhihi
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  useHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hideSummary: false
  showtoc: true
  tocopen: true
  
  assets:
    favicon: "/logo.png"
    favicon16x16: "/logo16.png"
    favicon32x32: "/logo32.png"

  profileMode:
    enabled: false
        
  homeInfoParams:
    Title: "![tamtamhihi](https://scontent-lhr6-1.xx.fbcdn.net/v/t39.30808-6/468745667_8746989062081623_2874682311296187016_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=a5f93a&_nc_ohc=c1Ok8Od3fVEQ7kNvgGPmOy_&_nc_oc=Adggb1IGsFN_3wzn8r5fJJC2z514RcTmUp9_aFaNcw4w6XjpVe_--KAPGXV9lP6Ktuc&_nc_zt=23&_nc_ht=scontent-lhr6-1.xx&_nc_gid=fDTalH84AcR5rsre3vaTTQ&oh=00_AYFCrWKkmsyuzLf3cDVxqnXv6lB7sf0_j98Axv0uMXZlGA&oe=67DA9360) tamtamhihi"
    Content: >
      just a lot of personal stuffs that I live, see and think about everyday.
  socialIcons:
    - name: github
      url: "https://github.com/tamtamhihi"
    - name: linkedin
      url: "https://www.linkedin.com/in/tam-nguyen-3097a8190/"
    - name: facebook
      url: "https://facebook.com/misa.nguyen.378"
    - name: email
      url: "mailto:tam.ngocbang.nguyen@gmail.com"
    - name: instagram
      url: "https://instagram.com/tamtamhihi"
  
  cover:
    hidden: false
    
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
      
pygmentsUseClasses: true

markup:
  highlight:
    noClasses: false
