baseURL: "https://tamtamhihi.github.io/"
title: "tamtamhihi's blog"
pagination:
  pagerSize: 5
theme: PaperMod
publishDir: docs

menu:
  main:
    - name: Archives
      url: /archives/
      weight: 10
    - name: Search
      url: /search/
      weight: 5
#    - name: Tags
#      url: /tags/
#      weight: 5
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

enableEmoji: true

params:
  env: production
  title: tamtamhihi
  description: "tamtamhihi's blog"
  keywords: [Blog]
  author: tamtamhihi
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  useHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hideSummary: false
  showtoc: true
  tocopen: true
  
  assets:
    favicon: "/logo.png"
    favicon16x16: "/logo16.png"
    favicon32x32: "/logo32.png"

  profileMode:
    enabled: false
        
  homeInfoParams:
    Title: "<img src=https://scontent-lhr6-2.xx.fbcdn.net/v/t39.30808-6/472210761_8921474947966366_1529229283651941521_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=833d8c&_nc_ohc=zO-nUkDfp7cQ7kNvgEppMUX&_nc_oc=Adh2ENgG51rqW8bxnWl52Dh33ePpm8Xchchh0mKU30v335wsTxb5GtxzwSWFs-n6VFk&_nc_zt=23&_nc_ht=scontent-lhr6-2.xx&_nc_gid=S1tcKVkTH1xS0lCz2EOKuA&oh=00_AYH-LkJsM8YSOF6wUX3mcEMLhddMdzFkHn_NHqU_PQ5amA&oe=67DA9D17 width=120 height=160/> tamtamhihi"
    Content: >
      just a lot of personal stuffs that I live, see and think about everyday.
  socialIcons:
    - name: github
      url: "https://github.com/tamtamhihi"
    - name: linkedin
      url: "https://www.linkedin.com/in/tam-nguyen-3097a8190/"
    - name: facebook
      url: "https://facebook.com/misa.nguyen.378"
    - name: email
      url: "mailto:tam.ngocbang.nguyen@gmail.com"
    - name: instagram
      url: "https://instagram.com/tamtamhihi"
  
  cover:
    hidden: false
    
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
      
pygmentsUseClasses: true

markup:
  highlight:
    noClasses: false
